### ISSUE TITLE
CM4 symbol uses pin 116 twice and is missing pin 118

### ISSUE THREAD

**Issue by HaasJona** [TheGuyDanish/CM4_MATX#30]
See screenshot: 
![Bildschirmfoto von 2020-12-14 14-38-34](https://user-images.githubusercontent.com/4310707/102087644-270a7280-3e1a-11eb-96e8-3f029d45653d.png)

**Comment by TheGuyDanish** [comment]
Good catch, will put the fix into my next commit within the hour.
