### ISSUE TITLE
pci express lines need ac coupling caps

### ISSUE THREAD

**Issue by HaasJona** [TheGuyDanish/CM4_MATX#31]
Should be 0402 size, 0.1µF, and on both lanes at the same position (inside the trace, not to ground).

**Comment by TheGuyDanish** [comment]
This would be good to add whenever we finish wiring up the PCI-e ports. I've currently only done to the preliminary signaling work, I'm still figuring out how to do power delivery and so forth. That said, if you'd like to do this, I'd be more than happy to accept pull requests for it.

**Comment by funkyguy4000** [comment]
I've started wiring this up. Keep in mind that the AC caps on the motherboard will only be on the TX lanes per the PCIe specification and PCIe design guidelines.

**Comment by TheGuyDanish** [comment]
Closed as of b87e19b
