### ISSUE TITLE
voltage of GPIO_VREF not defined

### ISSUE THREAD

**Issue by derwana** [TheGuyDanish/CM4_MATX#42]
GPIO_VREF is used on sheets (1,) 2 and 6 but never defined.

Screenshots from CM4_IO:
![Screenshot_2020-12-27_12-53-08](https://user-images.githubusercontent.com/37293191/103170162-8157fa00-4842-11eb-8a11-838a27dcf9b6.png)

![Screenshot_2020-12-27_12-49-50](https://user-images.githubusercontent.com/37293191/103170109-08f13900-4842-11eb-9714-400cb83cf796.png)

**Comment by TheGuyDanish** [comment]
J1 on CM4_HighSpeed
![Screenshot_20201227-125553](https://user-images.githubusercontent.com/5776313/103170226-fb887e80-4842-11eb-9e5d-8e29cccce86d.png)

I do want to potentially make this a solder jumper to 3.3v by default.

**Comment by TheGuyDanish** [comment]
Actually, disregard. Just read that schematic again. Yes, we do need to establish VREF voltage. Perhaps via the aforementioned jumper
