### ISSUE TITLE
Implement Real Time Clock

### ISSUE THREAD

**Issue by TheGuyDanish** [TheGuyDanish/CM4_MATX#49]
As mentioned in #1, we can quite easily implement an RTC into our design (which I believe would be a genuinely nice and useful feature). I'm breaking it out into a new issue to increase visibility.

> On-board RTC is present in the CM4IO board and could easily be lifted if we want to integrate it.
> ![image](https://user-images.githubusercontent.com/5776313/99153487-b0564a00-26a0-11eb-89ee-cb73ea135fb9.png)
> ![image](https://user-images.githubusercontent.com/5776313/99153489-b3513a80-26a0-11eb-954e-24f398292313.png)
_Originally posted by @TheGuyDanish in https://github.com/TheGuyDanish/CM4_MATX/issues/1#issuecomment-727240965_

**Comment by TheGuyDanish** [comment]
Looking further into this, I think using the NXP [PCF85263A ](https://www.mouser.dk/datasheet/2/302/PCF85263A-1127483.pdf) instead would be a better call. It has built-in circuitry for switching to battery power, meaning we can power the RTC with 3.3vSB when the power supply is powered and a coin cell battery when it isn't.

**Comment by derwana** [comment]
I'll take a look into it an do a schematic etc. in the new year.

**Comment by TheGuyDanish** [comment]
Closed by #51
