### ISSUE TITLE
Possibly boards to look at

### ISSUE THREAD

**Issue by ldrrp** [TheGuyDanish/CM4_MATX#54]
Perhaps some inspiration for ideas or things that may be unseen. But take a look at this. Delete this if you simply dont care or use this issue as a discussion about it. http://linuxgizmos.com/carrier-board-extends-raspberry-pi-compute-module-4-with-pcie-sata/

**Comment by TheGuyDanish** [comment]
I saw the overboard on Jeff Geerling's Pi PCI repo. I think it's interesting, and definitely something we could look to for inspiration. We do have Discussions enabled in the repo and would suggest a thread be raised for sharing these things over there, as they're a more proper forum for such things than issues.
