### ISSUE TITLE
Is there a PIN jumper to affect BOOT mode?

### ISSUE THREAD

**Issue by jcdutton** [TheGuyDanish/CM4_MATX#67]
On the Raspberry PI CM4 IO board, there is a jumper that affects the BOOT mode.
It is on Jumper 2 of the CM4 IO board:
Pin Function
1-2 nRPIBOOT If fitted forces USB booting, it is useful if the eMMC becomes corrupted.
3-4 EEPROM_nWP If fitted write protects the EEPROM on the CM4

It is vital when doing recovery of the eMMC on the CM4, or when installing the OS to it.

Please make sure there is a similar jumper on the CM4_MATX.

**Comment by TheGuyDanish** [comment]
These are fitted on J20. Which is near the bottom right of the board.

![image](https://user-images.githubusercontent.com/5776313/126069142-46fd6ed6-ce0d-418b-8edd-10581ae27c99.png)
